DROP TABLE IF EXISTS pets_diseases CASCADE;
DROP TABLE IF EXISTS pets_feeds CASCADE;
DROP TABLE IF EXISTS promos CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
DROP TABLE IF EXISTS passwords CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS users CASCADE;